import React from 'react';
import { LearningPathWeek } from '../../types/karmai';
import { BookOpen, Calendar, Clock, Sparkles, CheckCircle2, ArrowRight } from 'lucide-react';

interface PersonalizedLearningPathProps {
  weeks: LearningPathWeek[];
  onSelectCourse: (courseId: string) => void;
}

export const PersonalizedLearningPath: React.FC<PersonalizedLearningPathProps> = ({ weeks, onSelectCourse }) => {
  return (
    <div className="card-panel rounded-xl p-6 bg-white border border-slate-200 shadow-sm space-y-6">
      
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200 pb-4">
        <div>
          <h3 className="text-base font-extrabold text-slate-900 flex items-center gap-2">
            <BookOpen className="h-4 w-4 text-blue-700" />
            <span>14. My Personalized 30-Day Learning Roadmap</span>
          </h3>
          <p className="text-xs text-slate-600 font-medium mt-0.5">
            Tailored weekly progression generated by AI Engine 3 considering role gaps, course history, and priority skills.
          </p>
        </div>
        <span className="px-3 py-1 rounded text-xs font-bold bg-amber-50 text-amber-900 border border-amber-200">
          Structured 4-Week Plan
        </span>
      </div>

      {/* Timeline Grid */}
      <div className="space-y-4">
        {weeks.map((w) => (
          <div 
            key={w.weekNumber} 
            className="p-5 rounded-lg bg-slate-50 border border-slate-200 hover:border-slate-300 transition space-y-3"
          >
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-200 pb-2">
              <div className="flex items-center space-x-2">
                <span className="px-2.5 py-0.5 rounded bg-slate-900 text-white font-extrabold text-xs">
                  Week {w.weekNumber}
                </span>
                <h4 className="text-sm font-extrabold text-slate-900">{w.title}</h4>
              </div>

              <div className="flex items-center space-x-2 text-xs font-bold text-slate-600">
                <Clock className="h-3.5 w-3.5 text-amber-600" />
                <span>{w.duration}</span>
              </div>
            </div>

            <p className="text-xs text-slate-700 font-medium leading-relaxed">
              {w.description}
            </p>

            {/* Course Match Card */}
            <div className="p-3 rounded bg-white border border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-3 shadow-2xs">
              <div>
                <span className="text-[10px] font-bold text-blue-700 uppercase tracking-wider block">
                  Aligned iGOT Resource:
                </span>
                <span className="text-xs font-extrabold text-slate-900">{w.courseTitle}</span>
              </div>

              <button
                onClick={() => onSelectCourse(w.alignedCourseId)}
                className="px-3 py-1.5 rounded bg-blue-700 hover:bg-blue-800 text-white font-bold text-xs transition flex items-center space-x-1 border border-blue-800 shrink-0"
              >
                <span>Access Resource</span>
                <ArrowRight className="h-3.5 w-3.5 text-orange-300" />
              </button>
            </div>

            {/* Transparent AI Rationale */}
            <div className="p-3 rounded bg-blue-50/70 border border-blue-200 text-xs text-slate-800">
              <div className="font-bold text-blue-900 mb-0.5 flex items-center gap-1">
                <Sparkles className="h-3.5 w-3.5 text-orange-600" />
                <span>Why recommended?</span>
              </div>
              <p className="italic text-slate-700 text-[11px] font-medium">
                «{w.whyRecommended}»
              </p>
            </div>

          </div>
        ))}
      </div>

    </div>
  );
};
